Update net-61-whmcs

diff --git a/one-context.d/net-61-whmcs b/one-context.d/net-61-whmcs
--- a/one-context.d/net-61-whmcs
+++ b/one-context.d/net-61-whmcs
@@ -79,9 +79,9 @@ add_certificate () {
 	fi
 	if [ -z "${ipv4_private}" ]; then
 		if [ -n "$Site_name" ]; then
-			/usr/local/letsencrypt/./letsencrypt-auto --apache -d $Site_name --non-interactive --agree-tos -m example@gmail.com || echo "FAiled certificate" >> /etc/motd
-			echo "#!/bin/sh" > /opt/whmcs/whmcs_cert.sh
-			echo "cd /usr/local/letsencrypt && ./letsencrypt-auto certonly --apache --renew-by-default --apache -d $Site_name >> /var/log/'$Site_name'-renew.log 2>&1" >> /opt/whmcs/whmcs_cert.sh 
+			certbot --apache -d $Site_name --redirect --non-interactive --agree-tos -m example@gmail.com || echo "Failed certificate" >> /etc/motd
+			echo "#!/bin/bash" > /opt/whmcs/whmcs_cert.sh
+			echo "certbot renew" >> /opt/whmcs/whmcs_cert.sh 
 			echo "ETH0 found using a public IP. A certificate will be generated since a Site Name was found." >> /etc/motd
 		else
 			echo "ETH0 found using a public IP. No certificate will be configured as the Site name was not detected." >> /etc/motd
